### ISSUE TITLE
Not working, help apreciated

### ISSUE THREAD

**Issue by DragonInspire** [KM911/obsidian-execute-code-c-support#2]
when I click run I get

cc1plus.exe: fatal error: Obsidian\temp.cpp: No such file or directory
compilation terminated.

**Comment by KM911** [comment]
Could you provide more info to help me reproduce your results? 
For example , 
1. code block content 
2. obsidian-execute-c-support settings screenshot

**Comment by DragonInspire** [comment]
![Screenshot 2024-01-23 152533](https://github.com/KM911/obsidian-execute-code-c-support/assets/140202563/9be5369a-1d67-48b9-ba7b-c9698527d539)
![Screenshot 2024-01-23 152646](https://github.com/KM911/obsidian-execute-code-c-support/assets/140202563/42c4fc23-bc32-43ad-9876-d730ffa7fe03)

**Comment by KM911** [comment]
The problem is that your cling path contains whitespace. 
![image](https://github.com/KM911/obsidian-execute-code-c-support/assets/86272342/45401f9c-ae52-4b04-b3d7-544474b085fe)

To fix this, move the c-support.exe into another folder with an absolute path that does not contain whitespace.

**Comment by DragonInspire** [comment]
Thank you
